### ISSUE TITLE
[Bug Report] Possible timing issue

### ISSUE THREAD

**Issue by hugohadfield** [hugohadfield/kalmangrad#2]
Quoting @impredicative from https://github.com/hugohadfield/kalmangrad/issues/1
> A related point is that currently, there is no output data for the last input, but it would help for this to also exist if possible. Without this, I have to shift the outputs by 1 for them to align, and this shifting seems less than ideal. To me the last input is the most important input.

Could you produce a quick example bit of code showing the current behaviour and what your desired behaviour is? Then can work out if/where the bug is and squash it :bug: Thanks!

**Comment by impredicative** [comment]
I adjusted how I am creating my timestamps. I cannot reproduce this issue right now (which is a good thing). This issue can therefore be closed for now.
